### ISSUE TITLE
Advanced Bot Behavior

### ISSUE THREAD

**Issue by kilian2** [KielerGames/ringofsnakes#102] opened 2021-10-19 10:39 UTC
- [x] Stupid Bots should avoid leaving the map
- [ ] Add new type of Bot which implements the following behavior:
    - [x] actively collects food
    - [x] tries to avoid collisions 
    - [ ] can move parallel to another snake 
    - [ ] can flee from another snake

**Comment by tim-we** [comment] 2023-06-25 17:16
#217 is a duplicate of this (kinda). Closing this one because ä217 is more detailed.

**Closed by tim-we** 2023-06-25 17:16 UTC
Labels: enhancement, Server
